version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: transaction-parser
    restart: unless-stopped
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro    

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: unless-stopped

  transaction-parser:
    container_name: transaction-parser
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    volumes:
      - ./src/server/:/src/server
      - ./data:/src/server/data
