env:
  browser: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'prettier'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  prettier/prettier:
    - error
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
plugins:
  - 'prettier'
